<table align="left" width=100%>
    <tr>
        <td width="20%">
            <img src="faculty.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Faculty Notebook <br> (Session 7) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

# Topics of the Session 7: Introduction to Linear Algebra
-  Introduction to system of linear equations
-  Matrix Introduction 
- Types of Matrix

- Basic Matrix Transformations
- Determinant
- Matrix Inverse

- Vector properties and operations
- Linear Independence
- Row Reduced Echelon Form


In [2]:
import numpy as np
import sympy as sp
from sympy import symbols, Eq, solve

## 1. Introduction to System of Linear Equations
 ---------------------------------
 A system of linear equations is a collection of equations that involve the same set of variables.
 
 For example:
 
 2x + y = 8
 
 3x - y = 9

In [3]:
x, y, z = symbols('x y z')

# Example 1
# Two equations, two variables

eq1 = Eq(2*x + y, 8)
eq2 = Eq(3*x - y, 9)
solution1 = solve((eq1, eq2), (x, y))


In [4]:
# Example 2
# Three equations, three variables

eq3 = Eq(x + y + z, 6)
eq4 = Eq(2*x - y + z, 3)
eq5 = Eq(x - y - z, -2)
solution2 = solve((eq3, eq4, eq5), (x, y, z))

solution1, solution2

({x: 17/5, y: 6/5}, {x: 2, y: 5/2, z: 3/2})

## 2. Matrix Introduction
 ---------------------------------
 A matrix is a rectangular array of numbers arranged in rows and columns.
 They are widely used in linear algebra to represent systems of equations and transformations.

In [5]:

# Example 1
A = np.array([[1, 2], [3, 4]])

# Example 2
B = np.array([[5, 6, 7], [8, 9, 10]])

A, B

(array([[1, 2],
        [3, 4]]),
 array([[ 5,  6,  7],
        [ 8,  9, 10]]))

### 2.1 Types of Matrices
 ---------------------------------
 There are different types of matrices: Zero, Identity, Diagonal, Symmetric, etc.

In [6]:
from numpy import array
# list of data
data = [[11, 22],[33, 44],[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


In [7]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu

In [8]:
# define square matrix
M = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# lower triangular matrix
lower = tril(M)
print(lower)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [10]:
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [11]:
# diagonal matrix
from numpy import array
from numpy import diag

In [12]:
# define square matrix
M = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# extract diagonal vector
d = diag(M)
print(d)

[1 5 9]


In [14]:
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [15]:
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
from numpy import array
from numpy.linalg import inv

- A matrix Q is called orthogonal if $ Q.Q^T= I$  or $Q^T= Q^{-1}$

In [17]:
# define orthogonal matrix
Q = array([ 
[2,-2, 1],
[1, 2, 2],
[2,-1, -2]])
print(Q)

[[ 2 -2  1]
 [ 1  2  2]
 [ 2 -1 -2]]


In [18]:
# inverse equivalence
V = inv(Q)
#print(Q.T)
print(V)

[[ 0.0952381   0.23809524  0.28571429]
 [-0.28571429  0.28571429  0.14285714]
 [ 0.23809524  0.0952381  -0.28571429]]


In [19]:
# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 9  0  4]
 [ 0  9 -4]
 [ 4 -4  9]]


In [20]:
# define orthogonal matrix
Q = array([ 
[2,-2],
[1, 2]])
print(Q)

[[ 2 -2]
 [ 1  2]]


In [21]:
inv(Q)

array([[ 0.33333333,  0.33333333],
       [-0.16666667,  0.33333333]])

In [22]:
Q.T

array([[ 2,  1],
       [-2,  2]])

In [23]:

# Example 1
zero_matrix = np.zeros((2, 2))
identity_matrix = np.eye(3)

# Example 2
diagonal_matrix = np.diag([1, 2, 3])
symmetric_matrix = np.array([[1, 2], [2, 1]])

zero_matrix, identity_matrix, diagonal_matrix, symmetric_matrix

(array([[0., 0.],
        [0., 0.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]),
 array([[1, 2],
        [2, 1]]))

### 2.2 Matrix Creation and manipulation

In [24]:
# Create a matrix with all zeros
a = np.zeros((3,3))
print (a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# Create a 3 x 3matrix with all ones
b = np.ones((3,3))
print (b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
# Create a 3 x 3 matrix with the same constant 1.1
c = np.full((3,3), 1.1)
print (c)

[[1.1 1.1 1.1]
 [1.1 1.1 1.1]
 [1.1 1.1 1.1]]


In [27]:
# Create a 3 x 3 matrix  with random values
d = np.random.random((3,3))
print (d)

[[0.89424804 0.08296322 0.0471988 ]
 [0.80415386 0.8543994  0.79961026]
 [0.1928623  0.07349767 0.16408998]]


In [28]:
# Create a matrix with all elements specified. Each list is a row.
A=np.array([[1,2],[3,4],[5,6]])
print (A)
A.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [29]:
# Create 2 x 4 matrix (2 rows and 4 columns )
B=np.array([[1, 2, 3, 4], [11, 12, 13, 14]])
B

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

#### 2.2.2 Transpose of a matrix

In [30]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
# Transpose a matrix 
A.T

array([[1, 3, 5],
       [2, 4, 6]])

### 2.3 Matrix/Vector Algebra
All the basic arithmetic operations can be performed on vectors of same length. 

Addition and Subtraction: 
Both addition and subtraction can be performed using numpy. It is elementwise addition and subtraction ('+' & '-')

Vector Multiplication and Division: 
Both multiplication and division can be performed using numpy '*' and '/'.

In [32]:
A=np.array([[1,2],[3,4],[5,6]]) # Matrix of order 2 by 2
B=np.array([[11,12],[13,14],[15,16]]) # Matrix of order 2 by 2

In [33]:
# Addition:
C = A + B
C   # matrix of order 2 by 2

array([[12, 14],
       [16, 18],
       [20, 22]])

In [34]:
# Subtraction:
C= A-B
C

array([[-10, -10],
       [-10, -10],
       [-10, -10]])

In [35]:
# Multiplication ( Component wise Multiplication-Hardmard Product)
C = A * B
C

array([[11, 24],
       [39, 56],
       [75, 96]])

In [36]:
import numpy as np
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[11,12],[13,14],[15,16]])
A[0,0]/B[0,0]

0.09090909090909091

In [37]:
# Division is elementwise 
C=A/B
C

array([[0.09090909, 0.16666667],
       [0.23076923, 0.28571429],
       [0.33333333, 0.375     ]])

In [38]:
A*B # element wise called Hardmard product

array([[11, 24],
       [39, 56],
       [75, 96]])


### 2.4 Basic Matrix Transformations
 ---------------------------------
 Transformations include transpose, scalar multiplication, addition, and multiplication.

In [48]:
A=np.array([[1,2],[3,4]]) # Matrix of order 2 by 2
B=np.array([[11,12],[13,14]]) # Matrix of order 2 by 2



# Example 1
transpose_A = A.T
scalar_multiplication = 3 * A

# Example 2
matrix_addition = A + np.array([[2, 2], [2, 2]])
matrix_multiplication = A @ np.array([[2, 0], [1, 2]])

transpose_A, scalar_multiplication, matrix_addition, matrix_multiplication

(array([[1, 3],
        [2, 4]]),
 array([[ 3,  6],
        [ 9, 12]]),
 array([[3, 4],
        [5, 6]]),
 array([[ 4,  4],
        [10,  8]]))


### 2.3 Determinant
 ---------------------------------
 The determinant gives information about a matrix, such as invertibility and volume scaling.

In [49]:
# Example 1
det_A = np.linalg.det(A)

# Example 2
det_B = np.linalg.det(np.array([[2, 5], [1, 3]]))

det_A, det_B


(-2.0000000000000004, 1.0)

### 2.4 Matrix Inverse
 ---------------------------------
 The inverse of a matrix is such that A * A_inv = I.

In [50]:

# Example 1
A_inv = np.linalg.inv(A)
verification1 = np.round(A @ A_inv, 2)

# Example 2
C = np.array([[4, 7], [2, 6]])
C_inv = np.linalg.inv(C)
verification2 = np.round(C @ C_inv, 2)

A_inv, verification1, C_inv, verification2

(array([[-2. ,  1. ],
        [ 1.5, -0.5]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[ 0.6, -0.7],
        [-0.2,  0.4]]),
 array([[1., 0.],
        [0., 1.]]))

## 3. Vector Properties and Operations
 ---------------------------------
 Vectors are quantities with magnitude and direction.
 
 Common operations include addition, dot product, and cross product.

#### 3.1Row Vector
\begin{align}
    a &= \begin{bmatrix}
           1&2&3&4&5&6 \\
           \end{bmatrix}
  \end{align}

In [51]:
a = np.array([1, 2, 3, 4, 5, 6])  # 6 dimesional vector 
print(a)

[1 2 3 4 5 6]


In [52]:
#The shape and type of the vectors can be checked using array_name.shape and type(array_name)
a.shape

(6,)

In [53]:
type(a)

numpy.ndarray

#### 3.2 Column Vector
 \begin{align}
    a &= \begin{bmatrix}
           1 \\
           2 \\
           3 \\
           4 \\
           5 \\
           6 \\
         \end{bmatrix}
  \end{align}

In [54]:
# we can force a to be a column vector
a.shape=(6,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [55]:
b=a.transpose()
print(b)

[[1 2 3 4 5 6]]


#### 3.3 Vector Dot product and cross product

In [56]:
# This dot product can be thought of as product of two matrices
# a is matirx of order 1 by 6( row vector)
# b is a matrix of order 6 by 1( column vector)
a.dot(b) # Resultant matrix of order 6 by 6

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

##### Dot product
For 1-d arrays, the dot product/ inner product is defined using np.dot function.

For 2-D arrays, it is matrix multiplication which is done using matmul or a @ b.

If a scalar is multiplied with the vector, then it is equivalent to multiplying the scalar with all the elements of vector or matrix and using np.multiply (a, b) or a * b is preferred.

In [57]:
# Example 1
v1 = np.array([2, 3])
v2 = np.array([1, -1])
vector_add = v1 + v2
vector_dot = np.dot(v1, v2)

# Example 2
v3 = np.array([1, 0, 0])
v4 = np.array([0, 1, 0])
vector_cross = np.cross(v3, v4)
vector_norm = np.linalg.norm([3, 4])  # length of vector (3,4)

vector_add, vector_dot, vector_cross, vector_norm


(array([3, 2]), -1, array([0, 0, 1]), 5.0)

In [58]:
a = [[1, 2], [3, 4]]     
np.array(a)

array([[1, 2],
       [3, 4]])

In [59]:
b = [[5, 6], [7, 8]]
np.array(b)

array([[5, 6],
       [7, 8]])

In [60]:
# matrix-matrix multiplication
np.dot(a, b)         #[[1*5+2*7, 1*6+2*8], 
                     # [3*5+4*7, 3*6+4*8]]

array([[19, 22],
       [43, 50]])

#### 3.4  Addition substraction scalar multiplication of vectors

In [61]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
c = a + b # Addition of two vector
d = a-b   # Substraction of vctors
x = 2*a   # Scalar multiplication
print("The addition is",c)
print("The Substraction is",d)
print("The scalar multiplication is",x)

The addition is [3 6 9]
The Substraction is [-1 -2 -3]
The scalar multiplication is [2 4 6]


In [62]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
c = a + b # Addition of two vector
d = a-b   # Substraction of vctors
x = 2*a   # Scalar multiplication
print("The addition is",c)
print("The Substraction is",d)
print("The scalar multiplication is",x)

The addition is [3 6 9]
The Substraction is [-1 -2 -3]
The scalar multiplication is [2 4 6]


#### 3.5 Magnitude of a vector / Vector norm

The length of vector is called the magnitude / norm of the vector. 

There are Three norms - $L_1$ and $L_2$ and $L_\infty$ norms.

$L_1$ Norm - computes Manhattan distance $||u||_1 = |x_1|+|x_2|$

$L_2$ Norm - computes Euclidean distance. By default, it uses the L2 norm. $||u||_2=\sqrt(x_1^2+x_2^2)$ 

$L_\infty$ Norm - computes Chebeyshev norm  is also known as chessboard distance, since in the game of chess the minimum number of moves needed by a king to go from one square on a chessboard to another equals the Chebyshev distance between the centers of the squares
$||u||_\infty = max $\{|x_1|,|x_2|}

For $L_1$ norm, the argument, ord = 1 should be passed. 

In [63]:
u  = np.array([1,2,3,4,5])

In [64]:
u

array([1, 2, 3, 4, 5])

In [65]:
np.linalg.norm(u) # Euclidean Distance L_2 norm

7.416198487095663

In [66]:
np.linalg.norm(u, ord=2)

7.416198487095663

In [67]:
np.linalg.norm(u, ord=1) # Manhattan Distance

15.0

In [69]:
np.linalg.norm(u, ord=np.inf)

5.0

In [70]:
from scipy.spatial import distance
distance.chebyshev([1, 0, 0], [0, 1, 0]) # max{|1-0|,|0-1|,|0-0|}

1

#### 3.6 Cosine Similarity
$cos(\theta)= \frac{u.v}{||u||||v||}$

In [71]:
a = np.array([12000,34])
b = np.array([174,1500000])
cos_theta = np.dot(a,b)/[np.linalg.norm(a)*np.linalg.norm(b)] # Euclidean Distance]
cos_theta

array([0.00294932])

In [72]:
A

array([[1, 2],
       [3, 4]])

In [73]:
B

array([[11, 12],
       [13, 14]])

In [74]:
##### Multiplication Error

In [75]:
# matrix-matrix multiplication
np.dot(A,B)

array([[37, 40],
       [85, 92]])

In [76]:
# matrix-matrix multiplication 
# size should match!
np.dot(B,A)

#A.B is not the same as B.A

array([[47, 70],
       [55, 82]])

In [77]:
# coefficient matrix A and a vector b, The result is a vector
A=np.array([[1, 2],[3, 4]])
b=np.array([1, 2])

In [78]:
np.dot(A,b)

array([ 5, 11])

 ## 4. Linear Independence
 ---------------------------------
 Vectors are linearly independent if no vector can be written as a combination of others.


Check for linear combination of vectors. If it zero, then the set of vectors is linearly independent.

The no. of linearly independent columns will determine the no. of solutions.

Direction of two linearly dependent vectors is the same.

Determine whether the vectors are linearly independent of each other to see if the vectors form a basis,

or to determine how many independent equations there are, 

or to determine how many independent reactions there are.

The set S =$\{v_1, v_2, v_3\}$ of vectors in R3 is linearly independent if the only solution of

$c_1v_1 + c_2v_2 + c_3v_3 = 0 $
is $c_1, c_2, c_3 = 0 $



In [ ]:
u = np.array([[1],[0]])
v= np.array([[0],[1]])
w = np.array([[2], [1]])

In [ ]:
lin_combination = 2*u + 1*v
lin_combination    

In [ ]:
# Example 1
M1 = sp.Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
rank1 = M1.rank()
independence1 = rank1 == M1.shape[1]

# Example 2
M2 = sp.Matrix([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
rank2 = M2.rank()
independence2 = rank2 == M2.shape[1]

(rank1, independence1), (rank2, independence2)


## 5. Row Reduced Echelon Form (RREF)
 ---------------------------------
 RREF is a simplified form of a matrix that helps solve linear systems. RREF is a canonical form of a matrix where each leading entry in a row is 1, and is the only nonzero entry in its column. Rows of all zeros are at the bottom. This form makes it straightforward to solve linear systems, identify pivot variables, and check for consistency of equations.


In [79]:

# Example 1
M3 = sp.Matrix([[1, 2, -1, -4], [2, 3, -1, -11], [-2, 0, -3, 22]])
M3_rref = M3.rref()

# Example 2
M4 = sp.Matrix([[1, 2], [3, 4], [5, 6]])
M4_rref = M4.rref()

M3_rref, M4_rref

((Matrix([
  [1, 0, 0, -8],
  [0, 1, 0,  1],
  [0, 0, 1, -2]]),
  (0, 1, 2)),
 (Matrix([
  [1, 0],
  [0, 1],
  [0, 0]]),
  (0, 1)))